---
- name: Deploy Flask Application
  hosts: all
  become: yes
  vars_files:
    - "group_vars/all.yml"
    - "group_vars/{{ ansible_environment }}.yml"
  tasks:
    - name: Install system packages
      package:
        name:
          - python3
          - python3-pip
          - python3-venv
          - nginx
          - git
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present

    - name: Create Flask application directory
      file:
        path: "{{ flask_app_dir }}"
        state: directory
        owner: "{{ flask_user }}"
        group: "{{ flask_group }}"
        mode: '0755'

    - name: Clone Flask application repository
      git:
        repo: "{{ flask_app_repo }}"
        dest: "{{ flask_app_dir }}"
        version: main

    - name: Create Python virtual environment
      command: python3 -m venv ~/myvenv

    - name: Install Flask
      pip:
        requirements: "{{ flask_app_dir }}/requirements.txt"
        virtualenv: "~/myvenv"

    - name: Start App
      command: source ~/myvenv; python app.py --port {{ flask_port }}

    - name: Start App
      shell: |
        source ~/myvenv
        python app.py --port {{ flask_port }}
      environment:
        FLASK_ENV: "{{ ansible_environment }}"
      args:
        chdir: ~/myvenv


    - name: Notify about successful deployment
      debug:
        msg: "Flask application has been successfully deployed in the {{ ansible_environment }} environment on port {{ flask_port }}."
