---
- name: Deploy Flask Application
  hosts: all
  become: yes
  vars_files:
    - "group_vars/all.yml"
    - "group_vars/{{ ansible_environment }}.yml"
  tasks:
    - name: Install system packages
      package:
        name:
          - python3
          - python3-pip
          - python3-venv
          - nginx
          - git
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present
        
    - name: Create Flask application directory
      file:
        path: "{{ flask_app_dir }}"
        state: directory
        owner: "{{ flask_user }}"
        group: "{{ flask_group }}"
        mode: '0755'

    - name: Clone Flask application repository
      git:
        repo: "{{ flask_app_repo }}"
        dest: "{{ flask_app_dir }}"
        version: master

    - name: Create Python virtual environment
      command: python3 -m venv venv

    - name: Install Flask and Gunicorn
      pip:
        requirements: "{{ flask_app_dir }}/requirements.txt"
        virtualenv: "{{ flask_app_dir }}/venv"

    - name: Create Gunicorn systemd service file
      template:
        src: "templates/flask_app.service.j2"
        dest: "{{ flask_app_config_file }}"
        mode: '0644'

    - name: Start and enable Gunicorn service
      systemd:
        name: flask_app
        state: started
        enabled: yes

    - name: Create Nginx configuration file for Flask
      template:
        src: "templates/nginx_flask_app.conf.j2"
        dest: "{{ nginx_config_file }}"
        mode: '0644'

    - name: Enable Nginx site configuration
      command: "ln -s {{ nginx_config_file }} /etc/nginx/sites-enabled/flask_app"

    - name: Restart Nginx to apply configuration
      service:
        name: nginx
        state: restarted

    - name: Notify about successful deployment
      debug:
        msg: "Flask application has been successfully deployed in the {{ ansible_environment }} environment on port {{ flask_port }}."
