---
- name: Deploy Flask Application
  hosts: all
  become: yes
  vars_files:
    - "group_vars/all.yml"
    - "group_vars/{{ ansible_environment }}.yml"
  tasks:
    - name: Install system packages
      package:
        name:
          - python3
          - python3-pip
          - python3-venv
          - nginx
          - git
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present

    - name: Create Flask application directory
      file:
        path: "{{ flask_app_dir }}"
        state: directory
        owner: "{{ flask_user }}"
        group: "{{ flask_group }}"
        mode: '0755'

    - name: List Directory contents before cloning repository
      command: ls -al {{ flask_app_dir }}
      ignore_errors: yes

    - name: Delete Git Repo
      command: sudo rm -rf {{ flask_app_dir }}
      ignore_errors: yes

    - name: List Directory contents after deleting old Git repo
      command: ls -al {{ flask_app_dir }}
      ignore_errors: yes

    - name: Clone Flask application repository
      git:
        repo: "{{ flask_app_repo }}"
        dest: "{{ flask_app_dir }}"
        version: main

    - name: List Directory contents after cloning repository
      command: ls -al {{ flask_app_dir }}
            

    - name: Delete Python virtual environment
      command: sudo rm -rf ~/myvenv

    - name: Create Python virtual environment
      command: python3 -m venv ~/myvenv

    - name: List Directory contents after creating virtual environment
      command: ls -al ~/myvenv

    - name: Install Flask
      pip:
        requirements: "{{ flask_app_dir }}/requirements.txt"
        virtualenv: "~/myvenv"

    - name: Start App
      command: python app.py --port {{ flask_port }}

    - name: Notify about successful deployment
      debug:
        msg: "Flask application has been successfully deployed in the {{ ansible_environment }} environment on port {{ flask_port }}."
