---
 - hosts: all
   become: yes
   gather_facts: false
   tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: present
    - name: Starting httpd service
      service:
        name: httpd
        state: started

# How to run:
# ansible-playbook 1-install-and-configure-httpd.yml
# Open URLs on browser of both servers

