---
 - hosts: all
   become: yes
   gather_facts: false
   tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: present
    - template:
        src: index.html.j2
        dest: /usr/share/httpd/noindex/index.html
    - name: Starting httpd service
      service:
        name: httpd
        state: started

# How to run:
# ansible-playbook 2-install-and-configure-httpd.yml
# Open URLs on browser of both servers

