- name: Install and Configure Nginx with API Key
  hosts: all
  become: true
  vars:
    api_key: "your_api_key_value"
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Configure Nginx with API key
      template:
        src: nginx_config.j2
        dest: /etc/nginx/nginx.conf
      when: ansible_facts['os_family'] == 'Debian'
