- name: Install and Configure Nginx with API Key
  hosts: webservers
  vars_files:
    - nginx_secrets.yml
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present

    - name: Configure Nginx with API key
      template:
        src: nginx_config.j2
        dest: /etc/nginx/nginx.conf
      vars:
        api_key: "{{ api_key }}"

    - name: Start Nginx service
      service:
        name: nginx
        state: started
