---
- name: Detailed playbook to install and start httpd or apache2 based on OS
  hosts: localhost
  gather_facts: yes  # Gather facts to determine the OS
  become: yes  # Elevate privileges to perform administrative tasks
  tasks:
    - name: Install httpd on CentOS/RHEL
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      notify:
        - start httpd

    - name: Install apache2 on Debian/Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"
      notify:
        - start apache2

  handlers:
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: start apache2
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

  # Optional: Check and print status of the installed service
    - name: Gather service facts
      service_facts:

    - name: Print httpd service status (RedHat)
      debug:
        msg: "httpd service is {{ service_facts.services['httpd'].state }}"
      when: ansible_facts['os_family'] == "RedHat"

    - name: Print apache2 service status (Debian)
      debug:
        msg: "apache2 service is {{ service_facts.services['apache2'].state }}"
      when: ansible_facts['os_family'] == "Debian"
