---
- name: Install and configure Tomcat
  hosts: all
  gather_facts: true
  vars:
    req_java: java-1.8.0-openjdk
    set_java: jre-1.8.0-openjdk
    req_tomcat_ver: 9.0.41
    tomcat_url: http://mirrors.estointernet.in/apache/tomcat/tomcat-{{ req_tomcat_ver.split('.')[0] }}/v{{ req_tomcat_ver }}/bin/apache-tomcat-{{ req_tomcat_ver }}.tar.gz
    tomcat_port: 8090
  become: yes
  tasks:
    - name: Update necessary packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "{{ req_java }}"
      # Only update specific packages

    - name: Install required Java
      yum:
        name: "{{ req_java }}"
        state: present

    - name: Set default Java
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/{{ set_java }}/bin/java

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: /usr/local/apache-tomcat-{{ req_tomcat_ver }}.tar.gz
        mode: '0644'

    - name: Extract Tomcat
      unarchive:
        src: /usr/local/apache-tomcat-{{ req_tomcat_ver }}.tar.gz
        dest: /usr/local
        remote_src: yes
        creates: /usr/local/latest

    - name: Rename Tomcat directory
      command: mv /usr/local/apache-tomcat-{{ req_tomcat_ver }} /usr/local/latest
      args:
        removes: /usr/local/latest
      # Ensures idempotency

    - name: Replace default port with required port
      template:
        src: server.xml.j2
        dest: /usr/local/latest/conf/server.xml

    - name: Start Tomcat
      command: /usr/local/latest/bin/startup.sh
      args:
        chdir: /usr/local/latest/bin
        creates: /usr/local/latest/logs/catalina.out
      # Ensure Tomcat starts and is running
